name: fin_econ_2024

dependencies:
  - notebook=7.0.8
  - jupyterlab=4.0.11
  - ipykernel=6.28.0
  - numpy=1.26.4
  - pandas=2.2.2
  - numba=0.60.0
  - pandas-datareader=0.10.0
  - scipy=1.13.1
  - statsmodels=0.14.2
  - seaborn=0.13.2
  - pip=24.2
  - pip:
      - yfinance
      - fredapi
      - wrds
      - matplotlib
      - sympy
      - cvxopt
      - cvxpy
      - arch
      - scikit-learn